name: easyscraper
services:
  ui:
    image: ui
    build: ./ui
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${API_BASE_URL}
    healthcheck:
      test: curl -f http://localhost:3000/api/health
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5
    scale: 0
    depends_on:
      api:
        condition: service_healthy

  api:
    image: api
    build: ./api
    ports:
      - 8000:8000
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_DEFAULT_BUCKET=${MINIO_DEFAULT_BUCKET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: curl -f http://localhost:8000/health
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5
    scale: 1
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    hostname: "postgres1"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_volume:/data
    healthcheck:
      test: redis-cli ping
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5

  celery-worker:
    image: api
    build: ./api
    command: uv run celery -A app.celery.celery worker -l INFO -c 4
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_DEFAULT_BUCKET=${MINIO_DEFAULT_BUCKET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - celery_file_data:/app/celery_file_data
    healthcheck:
      test: uv run celery -A app.celery.celery inspect ping
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5
    scale: 1
    depends_on:
      redis:
        condition: service_healthy
  
  celery-insights:
    image: ghcr.io/danyi1212/celery-insights:latest
    ports:
      - 8555:8555
    environment:
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
    profiles: [dev]
  
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=easyscraper
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/live
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5

  create-minio-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb --ignore-existing myminio/${MINIO_DEFAULT_BUCKET};
      exit 0;
      "

  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 8080:8080
    environment:
      - BASE_URL=plantuml
    healthcheck:
      test: curl -f http://localhost:8080
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5
    profiles: [dev]

volumes:
  redis_volume:
  minio_data:
  celery_file_data:
  postgres_volume: