name: easyscraper
services:
  api:
    image: api
    build: ./api
    ports:
      - 8000:8000
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
    volumes:
      - sqlite_volume:/app/database
    healthcheck:
      test: curl -f http://localhost:8000/health
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4-management
    hostname: "rabbit1"
    environment:
      - RABBITMQ_DEFAULT_USER:${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS:${RABBITMQ_PASS}"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_volume:/data
    healthcheck:
      test: redis-cli ping
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5

  celery-worker-1:
    image: api
    build: ./api
    command: uv run celery -A app.celery.celery worker -l INFO -c 4
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
    volumes:
      - sqlite_volume:/app/database
    healthcheck:
      test: celery -b ${BROKER_URL} inspect ping
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 8080:8080
    environment:
      - BASE_URL=plantuml
    healthcheck:
      test: curl -f http://localhost:8080
      interval: 30s
      start_period: 10s
      timeout: 10s
      retries: 5
    profiles: [plantuml]

volumes:
  redis_volume:
  sqlite_volume:
  rabbitmq_volume: