@startuml
component Browser as browser
component "External Website" as ew
package "Docker Compose" as dc {
    component UI as ui
    component API as api
    component Redis as redis
    component Postgres as postgres
    component Minio as minio
    component "Celery Workers" as cw
}

browser -right-> ui
ui -right-> api
api -right-> redis : Broker &\nResult Backend
cw -left-> redis : Broker &\nResult Backend
cw -down-> postgres
cw -up-> minio : Save \nOutput Files
api -up-> minio : Download \nOutput Files
api -down-> postgres
cw -right-> ew : Scrape\nWebsite
redis --[hidden]u-> minio
redis --[hidden]d-> postgres
@enduml
