@startuml
title User Signup Sequence Diagram
participant Browser as browser
participant UI as ui
participant API as api
database Postgres as db

browser -> ui: User signup Page
ui -> browser: signup form
browser -> ui: username + password
ui -> api: POST /user/signup
api -> db: check if user exists
api -> api: hash password
api -> db: insert user
api -> ui: JWT token
ui -> ui: save token
ui -> browser: redirect to home page
@enduml
