@startuml
title User Login Sequence Diagram
participant Browser as browser
participant UI as ui
participant API as api
database SQLite as sqlite

browser -> ui: Home Page
ui -> ui: check if token exists and valid
ui -> browser: redirect to login page
browser -> ui: User Login Page
ui -> browser: login form
browser -> ui: username + password
ui -> api: POST /user/login
api -> sqlite: check if user exists
api -> api: verify password \nusing hash comparision
api -> api: generate JWT token
api -> ui: JWT token
ui -> ui: save token
ui -> browser: redirect to home page
@enduml
