[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "pydantic[email]>=2.9.2",
    "python-ulid[pydantic]>=3.0.0",
    "sqlmodel>=0.0.22",
]
