name: ci

on:
  push:

jobs:
  build-push-api:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/easyscraper-api:${{ github.sha }}

  build-push-ui:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./ui
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/easyscraper-ui:${{ github.sha }}